// Radiotchi - monolithic sprite roster for the 100-type morph (D21, revised).
//
// Each visible creature is ONE coherent 64x64 image (head+body connected), not a
// stack of layered parts: image generation gave us a clean full-body drawing per
// look, which removed the head/body gap the layered compose suffered from. The art
// is keyed to the two fields a player can SEE on the silhouette:
//
//   family (max stat, 5)  x  shape (deviation, 5)  =  25 adult looks
//
// The 2nd-stat "partner" (the 4-way split that fans 25 looks into the full 100
// types) is no longer drawn; it is surfaced as text on the Pet Detail screen. Mood
// is baked into the art too, so there is no separate eye overlay.
//
// Two pre-morph stages share the same scheme: one egg and a lineage-tinted child (5).
// Every creature also has a gentle 4-frame idle sway (rest, pose A, rest, pose B);
// `frame & 3` cycles it, driven by the app's animation timer (pet_render.c /
// ANIM_PERIOD_MS).
//
// Art is real 1-bit PNG generated by Codex (docs/codex-sprite-brief.md), ingested by
// tools/convert_art.py into icons/, compiled in by fbt (icons/<name>.png ->
// radiotchi_icons.h as `const Icon I_<name>;`) and drawn by reference with
// canvas_draw_icon - allocation-free, nothing large on the GUI draw stack.

#pragma once

#include <gui/gui.h>
#include <stdint.h>

#include "pet_growth.h" // PET_FAMILY_COUNT, PET_SHAPE_COUNT, ST_* family indices

#ifdef __cplusplus
extern "C" {
#endif

// All sprites share one 64x64 authoring grid and draw at the same cell origin
// (centered on cx,cy). `r` is accepted for API symmetry but ignored (size is fixed;
// see Q8). `frame` selects the idle pose (low 2 bits, a 4-phase sway).

// --- pre-morph life stages -------------------------------------------------
// One shared egg (level < PET_LEVEL_CHILD).
void pet_sprite_egg(Canvas* canvas, uint8_t frame, int cx, int cy, int r);
// Lineage-tinted child (level < PET_LEVEL_ADULT), foreshadowing the adult family.
void pet_sprite_child(Canvas* canvas, uint8_t family, uint8_t frame, int cx, int cy, int r);

// --- adult morph (one monolithic creature per family x shape) ----------------
void pet_sprite_character(
    Canvas* canvas,
    uint8_t family,
    uint8_t shape,
    uint8_t frame,
    int cx,
    int cy,
    int r);

#ifdef __cplusplus
}
#endif
