# Radiotchi - ingest the Codex-generated 1-bit sprites into icons/ for fbt.
#
# Source of truth is art/ (committed, image-generated by Codex; see
# docs/codex-sprite-brief.md). Each creature is one coherent 64x64 1-bit drawing
# (black ink on white), plus a 4-frame idle loop under art/idle/. The loop is a
# gentle sway - rest (0) -> pose A (1) -> rest (2 == 0) -> pose B (3) - so all four
# frames are ingested (suffix _0.._3) and the runtime cycles them every
# ANIM_PERIOD_MS via `frame & 3` (pet_sprites.c). Frame 2 duplicates frame 0 by
# design (the rest beat between the two sway poses); it is kept so the cycle reads
# straight off `frame & 3` with no remap.
#
# Output names match the symbols pet_sprites.c expects (fbt turns icons/<name>.png
# into `const Icon I_<name>`):
#   icons/char_<family>_<shape>_<f>.png   (25 chars x 4 frames)
#   icons/child_<family>_<f>.png          ( 5 children x 4)
#   icons/egg_<f>.png                     ( 1 egg x 4)
#
# The art is already 64x64 mode "1" (pure B/W), so this is mostly a guarded copy:
# we re-save through PIL convert("1") to guarantee the format fbt's png2xbm wants
# (1-bit, no alpha; black pixels become ink). Run: python tools/convert_art.py

from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
ART = ROOT / "art"
IDLE = ART / "idle"
OUT = ROOT / "icons"

CELL = 64
FAMILIES = ["mass", "vigor", "wild", "aura", "mind"]
SHAPES = ["pure", "sprout", "crested", "woven", "diffuse"]
FRAMES = [0, 1, 2, 3]  # full idle sway: rest, pose A, rest (==0), pose B


def ingest(stem):
    """Write icons/<stem>_<f>.png for each unique idle pose of `stem`."""
    for f in FRAMES:
        src = IDLE / f"{stem}_idle_{f}.png"
        if not src.exists():  # fall back to the static frame for pose 0
            src = ART / f"{stem}.png"
        im = Image.open(src).convert("1")
        if im.size != (CELL, CELL):
            im = im.resize((CELL, CELL), Image.NEAREST)
        dst = OUT / f"{stem}_{f}.png"
        im.save(dst)
        yield dst


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    n = 0
    for fam in FAMILIES:
        for sh in SHAPES:
            for _ in ingest(f"char_{fam}_{sh}"):
                n += 1
    for fam in FAMILIES:
        for _ in ingest(f"child_{fam}"):
            n += 1
    for _ in ingest("egg"):
        n += 1
    print(f"wrote {n} icons -> {OUT}")


if __name__ == "__main__":
    main()
